version: '3.9'

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    container_name: playwright
    working_dir: /app
    volumes:
      - .:/app # Mount the current project
      - ./test-results:/app/test-results # Persist test results
    command: >
      sh -c "npm ci &&
             npx playwright install &&
             npx playwright test"