name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
    inputs:
      test-folder:
        description: 'Folder containing tests to run'
        required: false
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Docker Compose
    - name: Run Playwright tests using Docker Compose
      run: docker-compose up --build --abort-on-container-exit

    # Upload Playwright test report as an artifact
    - name: Upload Playwright report
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: test-results/ 
        retention-days: 30